global:
  # serviceAccount: "default"
  # metacontrollerServiceAccount: "metacontroller"

shardCount: 1
namespace: jitsi

# extraPodSpec can be used to add tolerations and placement hints
# to any of the following components

haproxy:
  name: haproxy
  image: haproxy:2.3
  ingressEnable: true
  ingress:
    # can be alb
    class: haproxy
    host: jitsi.example.org
    tlsEnable: true
    # albGroup: global
jicofo:
  name: jicofo
  image: jitsi/jicofo:stable-6826
  imagePullPolicy: Always
  helathcheckEnable: true
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
  extraEnvs: []
jvb:
  name: jvb
  replicas: 2
  # Nodeports 30XXX will be used by default
  # you can use this variable to have several Jitsi cluster running on a cluster
  # specifying "31" will use ports 31XXX
  nodeportPrefix: "30"
  image: jitsi/jvb:stable-6826
  imagePullPolicy: Always
  monitoringEnable: true
  helathcheckEnable: true
  sysctlDaemonSetEnable: true
  resources:
    requests:
      cpu: 3000m
      memory: 3000Mi
  extraEnvs: []
prosody:
  name: prosody
  image: jitsi/prosody:stable-6826
  imagePullPolicy: Always
  monitoringEnable: true
  helathcheckEnable: true
  
  # Run the prosody pod as an unprivileged user with GID 0
  # Disable if you're deploying to an environment where user is handled for you
  # i.e. Openshift
  runUnprivileged: true

  resources:
    requests:
      memory: 300Mi
      cpu: 300m
  extraEnvs: []
  extraVolumes: []
  extraVolumeMounts: []
  globalModules: []
  globalConfig: []
web:
  name: web
  image: jitsi/web:stable-6826
  imagePullPolicy: Always
  ## kubectl create configmap -n <namespace> custom-config --from-file=custom-config.js
  customConfig: false
  ## kubectl create configmap -n <namespace> custom-ui --from-file=custom-interface_config.js
  customUi: false
  ## kubectl create configmap -n <namespace> plugin-head --from-file=plugin.head.html
  pluginHead: false
  ## kubectl create configmap -n <namespace> welcome-page-footer --from-file=welcomePageAdditionalContent.html
  welcomePageFooter: false
  ## kubectl create configmap -n <namespace> watermark --from-file=watermark.png
  customWatermark: false
  helathcheckEnable: true

  nginx:
    port: 80

    tls:
      enable: false
      port: 443

  resources:
    requests:
      cpu: 400m
      memory: 300Mi
      
  extraEnvs: []
  extraVolumes: []
  extraVolumeMounts: []

# if empty, the metacontroller will not be installed
# can be used to instantiate several Jitsi clusters on one Kubernetes cluster
metacontrollerNamespace: metacontroller

createSecret: true
JICOFO_AUTH_PASSWORD: ""
JICOFO_COMPONENT_SECRET: ""
JVB_AUTH_PASSWORD: ""

TZ: Europe/London

JVB_STUN_SERVERS: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
