global:
  # Uncomment and set these if you need to use privileged
  # service accounts for s6-overlay's UID/GID switching
  # at initialization time

  # serviceAccount: "default"

shardCount: 1
namespace: jitsi

haproxy:
  name: haproxy
  image: haproxy:2.4
  ingressEnable: true
  ingress:
    # can be alb
    class: haproxy
    host: jitsi.example.org
    tlsEnable: true
    # albGroup: global
  certmanager:
    issuer: letsencrypt-prod
  extraPodSpec: {}
jicofo:
  name: jicofo
  image: jitsi/jicofo:stable-7648-2
  imagePullPolicy: Always
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
  extraEnvs: []
  extraPodSpec: {}
jvb:
  name: jvb
  replicas: 2
  # Specify hostPort to use hostPort and not nodePort
  # Nodeports 30XXX will be used by default
  # you can use this variable to have several Jitsi cluster running on a cluster
  # specifying "31" will use ports 31XXX
  nodeportPrefix: "30"
  image: jitsi/jvb:stable-7648-2
  imagePullPolicy: Always
  monitoringEnable: true
  sysctlDaemonSetEnable: true
  resources:
    requests:
      cpu: 3000m
      memory: 3000Mi
  extraEnvs: []
  extraPodSpec: {}
prosody:
  name: prosody
  image: jitsi/prosody:stable-7648-2
  imagePullPolicy: Always
  monitoringEnable: true
  resources:
    requests:
      memory: 300Mi
      cpu: 300m
  extraEnvs: []
  extraPodSpec: {}
  extraVolumes: []
  extraVolumeMounts: []
  globalModules: []
  globalConfig: []
web:
  name: web
  replicas: 2
  image: jitsi/web:stable-7648-2
  imagePullPolicy: Always
  ## kubectl create configmap -n <namespace> custom-config --from-file=custom-config.js
  customConfig: false
  ## kubectl create configmap -n <namespace> custom-ui --from-file=custom-interface_config.js
  customUi: false
  ## kubectl create configmap -n <namespace> plugin-head --from-file=plugin.head.html
  pluginHead: false
  ## kubectl create configmap -n <namespace> welcome-page-footer --from-file=welcomePageAdditionalContent.html
  welcomePageFooter: false
  ## kubectl create configmap -n <namespace> watermark --from-file=watermark.png
  customWatermark: false
  resources:
    requests:
      cpu: 400m
      memory: 300Mi
  extraEnvs: []
  extraPodSpec: {}
  extraVolumes: []
  extraVolumeMounts: []

createSecret: true
JICOFO_AUTH_PASSWORD: ""
JICOFO_COMPONENT_SECRET: ""
JVB_AUTH_PASSWORD: ""

TZ: Europe/London

JVB_STUN_SERVERS: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
