{{ if (gt ($.Values.shardCount | int) 1) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "jitsi.haproxy.labels" $ | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  selector: {{ include "jitsi.haproxy.selectorLabels" $ | nindent 6 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}-0
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "jitsi.haproxy.labels" $ | nindent 4 }}
spec:
  ports:
  - name: peering
    port: 1024
    targetPort: peering
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Values.haproxy.name }}-0
    {{ include "jitsi.haproxy.labels" $ | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}-1
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "jitsi.haproxy.labels" $ | nindent 4 }}
spec:
  ports:
  - name: peering
    port: 1024
    targetPort: peering
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Values.haproxy.name }}-1
    {{ include "jitsi.haproxy.labels" $ | nindent 4 }}
  type: ClusterIP
{{ end -}}
