{{ if (gt ($.Values.shardCount | int) 1) -}}
apiVersion: v1
data:
  haproxy.cfg: |
    {{ tpl (.Files.Get "configs/haproxy/haproxy.cfg") . | nindent 4 }}
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "jitsi.haproxy.labels" $ | nindent 4 }}
{{ end -}}
