apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  selector:
    k8s-app: {{ $.Values.haproxy.name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}-0
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: peering
    port: 1024
    targetPort: peering
  selector:
   statefulset.kubernetes.io/pod-name: {{ $.Values.haproxy.name }}-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}-1
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: peering
    port: 1024
    targetPort: peering
  selector:
   statefulset.kubernetes.io/pod-name: {{ $.Values.haproxy.name }}-1
  type: ClusterIP
