{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "jitsi.jvbShard.labels" (merge (dict "RelativeScope" (dict "shard" $shard)) $) | nindent 4 }}
  name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-jvb
  namespace: {{ $.Release.Namespace }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "metrics"
    protocol: "TCP"
    port: 9888
    targetPort: metrics
  selector: {{ include "jitsi.jvbShard.selectorLabels" (merge (dict "RelativeScope" (dict "shard" $shard)) $) | nindent 4 }}
{{- range $replica, $f := until (int $.Values.jvb.replicas) }}
{{ if empty $.Values.jvb.hostPort }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "jitsi.jvbReplica.labels" (merge (dict "RelativeScope" (dict "shard" $shard "replica" $replica)) $) | nindent 4 }}
  name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-jvb-{{ $replica }}-ice
  namespace: {{ $.Release.Namespace }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: "jvb-udp"
    protocol: "UDP"
    port: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
    targetPort: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
    nodePort: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-jvb-{{ $replica }}
    {{ include "jitsi.jvbShard.labels" (merge (dict "RelativeScope" (dict "shard" $shard)) $) | nindent 4 }}
{{ end -}}
{{ end -}}
{{ end -}}
