apiVersion: v1
data:
  graceful_shutdown.sh: |
    {{- .Files.Get "configs/jvb/graceful_shutdown.sh" | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    scope: jitsi
  name: jvb-shutdown
  namespace: {{ $.Release.Namespace }}
