{{- if $.Values.jvb.gracefulShutdownConfigMap.create }}
apiVersion: v1
data:
  graceful_shutdown.sh: |
    {{- .Files.Get "configs/jvb/graceful_shutdown.sh" | nindent 4 }}
kind: ConfigMap
metadata:
  labels: {{ include "jitsi.jvbGlobal.labels" $ | nindent 4 }}
  name: {{ $.Values.jvb.gracefulShutdownConfigMap.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
