{{- if $.Values.jvb.entryPointConfigMap.create }}
apiVersion: v1
data:
  entrypoint.sh: |
    {{- tpl (.Files.Get "configs/jvb/entrypoint.sh") . | nindent 4 }}
kind: ConfigMap
metadata:
  labels: {{ include "jitsi.jvbGlobal.labels" $ | nindent 4 }}
  name: {{ include "jitsi.jvb.entryPointConfigMap.name" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
