{{- if $.Values.jvb.entryPointConfigMap.create }}
apiVersion: v1
data:
  entrypoint.sh: |
    {{- tpl (.Files.Get "configs/jvb/entrypoint.sh") . | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    scope: jitsi
  {{- with $.Values.jvb.extraLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $.Values.jvb.entryPointConfigMap.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
