{{- range $shard, $e := until (int $.Values.shardCount) }}
{{- range $replica, $f := until (int $.Values.jvb.replicas) }}
{{ if empty $.Values.jvb.hostPort }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "jitsi.jvbReplica.labels" (merge (dict "RelativeScope" (dict "shard" $shard "replica" $replica)) $) | nindent 4 }}
  name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}-ice
  namespace: {{ $.Release.Namespace }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: "jvb-udp"
    protocol: "UDP"
    port: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
    targetPort: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
    nodePort: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
  selector:
    statefulset.kubernetes.io/pod-name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}
    {{ include "jitsi.jvbShard.labels" (merge (dict "RelativeScope" (dict "shard" $shard)) $) | nindent 4 }}
{{ end -}}
---
apiVersion: v1
kind: Service
metadata:
{{ with $.Values.jvb.monitoring.service.extraAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{ end }}
  labels: {{ include "jitsi.jvbReplicaMonitoring.labels" (merge (dict "RelativeScope" (dict "shard" $shard "replica" $replica)) $) | nindent 4 }}
  name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}-metrics
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: "metrics"
    protocol: "TCP"
    port: 9888
    targetPort: metrics
  selector:
    statefulset.kubernetes.io/pod-name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}
    {{ include "jitsi.jvbShard.labels" (merge (dict "RelativeScope" (dict "shard" $shard)) $) | nindent 4 }}
{{ end -}}
{{ end -}}
