{{- range $shard, $e := until (int $.Values.shardCount) }}
{{- range $replica, $f := until (int $.Values.jvb.replicas) }}
{{ if empty $.Values.jvb.hostPort }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    scope: jitsi
    service: jvb
    shard: {{ $shard | quote }}
    replica: {{ $replica | quote }}
  name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}-ice
  namespace: {{ $.Release.Namespace }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: "jvb-udp"
    protocol: "UDP"
    port: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
    targetPort: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
    nodePort: {{ $.Values.jvb.nodeportPrefix }}{{ add $shard 3 }}{{ printf "%02d" $replica }}
  selector:
    statefulset.kubernetes.io/pod-name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}
    scope: jitsi
    shard: {{ $shard | quote }}
{{ end -}}
---
apiVersion: v1
kind: Service
metadata:
{{ if $.Values.jvb.monitoring.service.extraAnnotations }}
  annotations:
{{ $.Values.jvb.monitoring.service.extraAnnotations | toYaml | nindent 4 }}
{{ end }}
  labels:
    scope: jitsi
    service: jvb
    shard: {{ $shard | quote }}
    replica: {{ $replica | quote }}
    {{- if $.Values.jvb.monitoring.service.extraLabels }}
    {{- $.Values.jvb.monitoring.service.extraLabels | toYaml | nindent 4 }}
    {{- end }}
  name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}-metrics
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: "metrics"
    protocol: "TCP"
    port: 9888
    targetPort: metrics
  selector:
    statefulset.kubernetes.io/pod-name: shard-{{ $shard }}-{{ $.Values.jvb.name }}-{{ $replica }}
    scope: jitsi
    shard: {{ $shard | quote }}
{{ end -}}
{{ end -}}
