{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "jitsi.prosodyShard.labels" (merge (dict "RelativeScope" .) $) | nindent 4 }}
  name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-prosody
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: c2s
    port: 5222
    targetPort: c2s
  - name: http
    port: 5280
    targetPort: http
  selector: {{ include "jitsi.prosodyShard.selectorLabels" (merge (dict "RelativeScope" .) $) | nindent 4 }}
{{ end }}
