{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "jitsi.prosodyShard.labels" (merge (dict "RelativeScope" .) $) | nindent 4 }}
  annotations:
    configmap-hash: {{ include "jitsi.sharedConfigMap.hash" $ }}
  {{- with $.Values.prosody.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-prosody
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "jitsi.prosodyShard.selectorLabels" (merge (dict "RelativeScope" .) $) | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "jitsi.prosodyShard.labels" (merge (dict "RelativeScope" .) $) | nindent 8 }}
      annotations:
        configmap-hash: {{ include "jitsi.sharedConfigMap.hash" $ }}
      {{ if $.Values.prosody.monitoringEnable  }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "5280"
      {{ end }}
      {{- with $.Values.prosody.extraAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with $.Values.prosody.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if (($.Values.global).serviceAccount) }}
      serviceAccountName: {{ (($.Values.global).serviceAccount) }}
    {{- else }}
      automountServiceAccountToken: false
    {{- end }}
    {{- if $.Values.prosody.imagePullSecrets }}
      imagePullSecrets:
      {{- range $secretName := $.Values.prosody.imagePullSecrets }}
      - name: {{ $secretName }}
      {{- end }}
    {{- end }}
      volumes:
        - name: prosody
          configMap:
            name: {{ include "jitsi.name" $ }}-prosody-config
            items:
              - key: mod_prometheus.lua
                path: mod_prometheus.lua
              - key: mod_measure_stanza_counts.lua
                path: mod_measure_stanza_counts.lua
              - key: mod_measure_client_presence.lua
                path: mod_measure_client_presence.lua
      {{- if $.Values.prosody.extraVolumes }}
        {{- toYaml $.Values.prosody.extraVolumes | nindent 8 }}
      {{- end }}
      containers:
        - name: prosody
        {{- with $.Values.prosody.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- if $.Values.prosody.image }}
          image: {{ $.Values.prosody.image }}
        {{- else }}
          image: jitsi/prosody:{{ $.Chart.AppVersion }}
        {{- end }}
          imagePullPolicy: {{ $.Values.prosody.imagePullPolicy }}
          {{ if $.Values.prosody.monitoringEnable -}}
          ports:
          - containerPort: 5280
            protocol: TCP
            name: http
          - containerPort: 5222
            protocol: TCP
            name: c2s
          {{ end -}}
          readinessProbe:
            ## the command that is called obeys standard exit codes
            exec:
              command:
                - prosodyctl
                - --config
                - /config/prosody.cfg.lua
                - status
          startupProbe:
            ## the command that is called obeys standard exit codes
            exec:
              command:
                - prosodyctl
                - --config
                - /config/prosody.cfg.lua
                - status
          livenessProbe:
            ## the command that is called obeys standard exit codes
            exec:
              command:
                - prosodyctl
                - --config
                - /config/prosody.cfg.lua
                - status
          volumeMounts:
          {{ if $.Values.prosody.monitoringEnable -}}
          # add-ons that allow exporting of metrics to prometheus (mod_prometheus.lua)
          # or enrich the available stats (mod_measure_stanza_counts.lua,
          # mod_measure_client_presence.lua)
          - name: prosody
            mountPath: /prosody-plugins-custom/mod_prometheus.lua
            subPath: mod_prometheus.lua
          - name: prosody
            mountPath: /usr/lib/prosody/modules/mod_measure_stanza_counts.lua
            subPath: mod_measure_stanza_counts.lua
          - name: prosody
            mountPath: /usr/lib/prosody/modules/mod_measure_client_presence.lua
            subPath: mod_measure_client_presence.lua
          {{ end -}}
        {{- if $.Values.prosody.extraVolumeMounts }}
          {{- toYaml $.Values.prosody.extraVolumeMounts | nindent 10 }}
        {{- end }}
          env:
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_MUC_MODULES
              value: muc_meeting_id,muc_domain_mapper
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi.sharedSecret.name" $ }}
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi.sharedSecret.name" $ }}
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi.sharedSecret.name" $ }}
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ include "jitsi.sharedConfigMap.name" $ }}
                  key: TZ
            {{ if $.Values.prosody.monitoringEnable }}
            # activate add-ons that enrich the available stats of prosody
            - name: GLOBAL_MODULES
              value: prometheus,measure_stanza_counts,measure_client_presence{{- if $.Values.prosody.globalModules -}},{{- join "," $.Values.prosody.globalModules -}}{{- end }}
            # config to allow exporting metrics in prometheus format by prometheus add-on
            - name: GLOBAL_CONFIG
              value: statistics = "internal";\nstatistics_interval = 15;{{- if $.Values.prosody.globalConfig -}}\n{{- join ";\\n" $.Values.prosody.globalConfig -}};{{- end }}
            {{ else }}
            {{- if $.Values.prosody.globalModules }}
            - name: GLOBAL_MODULES
              value: {{- join "," $.Values.prosody.globalModules }}
            {{ end -}}
            {{- if $.Values.prosody.globalConfig }}
            - name: GLOBAL_CONFIG
              value: {{- join ";\\n" $.Values.prosody.globalConfig }}
            {{ end -}}
            {{ end }}
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "jitsi.sharedConfigMap.name" $ }}
                  key: PUBLIC_URL
          {{- if $.Values.uvs.enable }}
            - name: ENABLE_AUTH
              value: "1"
            - name: AUTH_TYPE
              value: "matrix"
            - name: MATRIX_UVS_URL
              value: "{{ include "jitsi.name" $ }}-uvs.{{ $.Release.Namespace }}.svc.cluster.local"
            - name: MATRIX_UVS_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "jitsi.sharedConfigMap.name" $ }}
                  key: PUBLIC_URL
            - name: MATRIX_UVS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: UVS_AUTH_TOKEN
                  name: {{ include "jitsi.sharedSecret.name" $ }}
                  optional: false
            - name: MATRIX_UVS_SYNC_POWER_LEVELS
              value: "{{ $.Values.uvs.syncPowerLevels }}"
          {{- end }}
          {{- if $.Values.prosody.extraEnvs }}
            {{- toYaml $.Values.prosody.extraEnvs | nindent 12 }}
          {{- end }}
        {{- with $.Values.prosody.extraContainerSpec }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{ end }}
