{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    scope: jitsi
    service: {{ $.Values.prosody.name }}
    shard: {{ $shard | quote}}
  {{- with $.Values.prosody.extraLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: shard-{{ $shard }}-{{ $.Values.prosody.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: c2s
    port: 5222
    targetPort: c2s
  - name: http
    port: 5280
    targetPort: http
  selector:
    k8s-app: {{ $.Values.prosody.name }}
    scope: jitsi
    shard: {{ $shard | quote}}
{{ end }}
