apiVersion: v1
data:
  JICOFO_AUTH_PASSWORD: {{ if $.Values.JICOFO_AUTH_PASSWORD }}{{ $.Values.JICOFO_AUTH_PASSWORD | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  JICOFO_COMPONENT_SECRET: {{ if $.Values.JICOFO_COMPONENT_SECRET }}{{ $.Values.JICOFO_COMPONENT_SECRET | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
  JVB_AUTH_PASSWORD: {{ if $.Values.JVB_AUTH_PASSWORD }}{{ $.Values.JVB_AUTH_PASSWORD | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
kind: Secret
metadata:
  labels:
    scope: jitsi
  name: jitsi-secrets
  namespace: {{ $.Values.namespace }}
type: Opaque
