{{- if $.Values.createSecret -}}
apiVersion: v1
data:
  JICOFO_AUTH_PASSWORD: {{ required "JICOFO_AUTH_PASSWORD is required" $.Values.JICOFO_AUTH_PASSWORD | b64enc }}
  JICOFO_COMPONENT_SECRET: {{ required "JICOFO_COMPONENT_SECRET is required" $.Values.JICOFO_COMPONENT_SECRET | b64enc }}
  JVB_AUTH_PASSWORD: {{ required "JVB_AUTH_PASSWORD is required" $.Values.JVB_AUTH_PASSWORD | b64enc }}
{{- if $.Values.uvs.enable }}
  UVS_AUTH_TOKEN: {{ required "uvs.secrets.AUTH_TOKEN is required if UVS is enabled" $.Values.uvs.secrets.AUTH_TOKEN | b64enc }}
{{- if eq (include "jitsi.uvsAccessTokenSecret.name" $) (include "jitsi.sharedSecret.name" $) }}
  UVS_ACCESS_TOKEN: {{ required "uvs.secrets.ACCESS_TOKEN is required if UVS is enabled" $.Values.uvs.secrets.ACCESS_TOKEN | b64enc }}
{{- end }}
{{- end }}
kind: Secret
metadata:
  labels: {{ include "jitsi.config.labels" $ | nindent 4 }}
  name: {{ include "jitsi.sharedSecret.name" $ }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
{{- end }}
