# see https://github.com/GoogleCloudPlatform/metacontroller/tree/master/examples/service-per-pod
{{ if ne $.Values.metacontrollerNamespace "" -}}
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: jitsi-service-per-pod
  labels:
    scope: jitsi
spec:
  resources:
  - apiVersion: apps/v1
    resource: statefulsets
    annotationSelector:
      matchExpressions:
      - {key: jitsi-service-per-pod-label, operator: Exists}
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    sync:
      webhook:
        url: http://jitsi-service-per-pod.{{ $.Values.metacontrollerNamespace }}/sync-service-per-pod
    finalize:
      webhook:
        url: http://jitsi-service-per-pod.{{ $.Values.metacontrollerNamespace }}/finalize-service-per-pod
{{ end -}}
