apiVersion: v1
data:
  {{ include "jitsi.sharedconfigmap.data" $ | nindent 2 }}
kind: ConfigMap
metadata:
  labels:
    scope: jitsi
  name: {{ $.Values.sharedConfigMapName }}
  namespace: {{ $.Release.Namespace }}
