apiVersion: v1
data:
  {{ include "jitsi.sharedconfigmap.data" $ | nindent 2 }}
kind: ConfigMap
metadata:
  labels:
    scope: jitsi
  {{- with $.Values.sharedConfigMapExtraLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $.Values.sharedConfigMapName }}
  namespace: {{ $.Release.Namespace }}
