apiVersion: v1
data:
  {{ include "jitsi.sharedConfigMap.data" $ | nindent 2 }}
kind: ConfigMap
metadata:
  labels: {{ include "jitsi.config.labels" $ | nindent 4 }}
  name: {{ include "jitsi.sharedConfigMap.name" $ }}
  namespace: {{ $.Release.Namespace }}
