apiVersion: v1
data:
  {{ include "jitsi.sharedconfigmap.data" $ | nindent 2 }}
kind: ConfigMap
metadata:
  labels: {{ include "jitsi.config.labels" $ | nindent 4 }}
  name: {{ $.Values.sharedConfigMapName }}
  namespace: {{ $.Release.Namespace }}
