apiVersion: v1
data:
  JVB_STUN_SERVERS: {{ $.Values.JVB_STUN_SERVERS }}
  PUBLIC_URL: {{ if $.Values.PUBLIC_URL }}{{ $.Values.PUBLIC_URL }}{{ else }}{{ if $.Values.haproxy.ingress.tlsEnable }}{{ print "https://" $.Values.haproxy.ingress.host }}{{ else }}{{ print "http://" $.Values.haproxy.ingress.host }}{{ end }}{{ end }}
  TZ: {{ $.Values.TZ }}
kind: ConfigMap
metadata:
  labels:
    scope: jitsi
  name: jitsi-config
  namespace: {{ $.Values.namespace }}
