# This daemon set increases network buffer size on nodes hosting the JVBs
# cf https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf
{{ if $.Values.jvb.sysctlDaemonSetEnable -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: sysctl-jvb
    scope: jitsi
    {{- with $.Values.sysctljvb.extraLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  annotations:
    configmap-hash: {{ include "jitsi.sharedconfigmap.hash" $ }}
  {{- with $.Values.sysctljvb.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: sysctl-jvb
  namespace: {{ $.Release.Namespace }}
spec:
{{- if not (($.Values.global).serviceAccount) }}
  automountServiceAccountToken: false
{{- end }}
  selector:
    matchLabels:
      k8s-app: sysctl-jvb
      scope: jitsi
  template:
    metadata:
      labels:
        k8s-app: sysctl-jvb
        scope: jitsi
    {{- with $.Values.sysctljvb.extraLabels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.sysctljvb.extraAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with $.Values.sysctljvb.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
      hostNetwork: yes
      containers:
      - name: sysctl-jvb
        image: {{ $.Values.sysctljvb.image }}
        imagePullPolicy: {{ $.Values.sysctljvb.imagePullPolicy }}
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -o errexit
          set -o xtrace
          while sysctl -w net.core.rmem_max=10485760 net.core.wmem_max=10485760 net.core.netdev_max_backlog=100000
          do
            sleep 60s
          done
      {{- with $.Values.sysctljvb.extraContainerSpec }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end -}}
