# This daemon set increases network buffer size on nodes hosting the JVBs
# cf https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf
{{ if $.Values.jvb.sysctlDaemonSetEnable -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: {{ include "jitsi.sysctlJvb.labels" $ | nindent 4 }}
  annotations:
    configmap-hash: {{ include "jitsi.sharedConfigMap.hash" $ }}
  {{- with $.Values.sysctljvb.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "jitsi.name" . }}-sysctl-jvb
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels: {{ include "jitsi.sysctlJvb.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels: {{ include "jitsi.sysctlJvb.labels" $ | nindent 8 }}
    {{- with $.Values.sysctljvb.extraLabels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
      annotations:
        configmap-hash: {{ include "jitsi.sharedConfigMap.hash" $ }}
    {{- with $.Values.sysctljvb.extraAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with $.Values.sysctljvb.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if (($.Values.global).serviceAccount) }}
      serviceAccountName: {{ (($.Values.global).serviceAccount) }}
    {{- else }}
      automountServiceAccountToken: false
    {{- end }}
      hostNetwork: yes
    {{- if $.Values.sysctljvb.imagePullSecrets }}
      imagePullSecrets:
      {{- range $secretName := $.Values.sysctljvb.imagePullSecrets }}
      - name: {{ $secretName }}
      {{- end }}
    {{- end }}
      containers:
      - name: sysctl-jvb
        image: {{ $.Values.sysctljvb.image }}
        imagePullPolicy: {{ $.Values.sysctljvb.imagePullPolicy }}
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -o errexit
          set -o xtrace
          while sysctl -w net.core.rmem_max=10485760 net.core.wmem_max=10485760 net.core.netdev_max_backlog=100000
          do
            sleep 60s
          done
      {{- with $.Values.sysctljvb.extraContainerSpec }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end -}}
