{{ if $.Values.uvs.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi.name" $ }}-uvs-wellknown
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "jitsi.uvs.labels" $ | nindent 4 }}
data:
  jitsi: "{\"auth\": \"openidtoken-jwt\"}"
{{ end -}}
