{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "jitsi.webShard.labels" (merge (dict "RelativeScope" .) $) | nindent 4 }}
  name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-web
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ $.Values.web.httpPort }}
    targetPort: http
  selector: {{ include "jitsi.webShard.selectorLabels" (merge (dict "RelativeScope" .) $) | nindent 4 }}
{{- end }}
