apiVersion: v1
kind: Service
metadata:
  labels:
    scope: jitsi
    service: {{ $.Values.web.name }}
  name: {{ $.Values.web.name }}
  namespace: {{ $.Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: {{ $.Values.web.nginx.port | int | default 80 }}
  selector:
    k8s-app: {{ $.Values.web.name }}
    scope: jitsi
