{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "jitsi.webShard.labels" (merge (dict "RelativeScope" .) $) | nindent 4 }}
  annotations:
    configmap-hash: {{ include "jitsi.sharedConfigMap.hash" $ }}
  {{- with $.Values.web.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-web
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ $.Values.web.replicas }}
  selector:
    matchLabels: {{ include "jitsi.webShard.selectorLabels" (merge (dict "RelativeScope" .) $) | nindent 8 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "jitsi.webShard.labels" (merge (dict "RelativeScope" .) $) | nindent 8 }}
      annotations:
        configmap-hash: {{ include "jitsi.sharedConfigMap.hash" $ }}
      {{- with $.Values.web.extraAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with $.Values.web.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- if (($.Values.global).serviceAccount) }}
      serviceAccountName: {{ (($.Values.global).serviceAccount) }}
    {{- else }}
      automountServiceAccountToken: false
    {{- end }}
    {{- if $.Values.web.imagePullSecrets }}
      imagePullSecrets:
      {{- range $secretName := $.Values.web.imagePullSecrets }}
      - name: {{ $secretName }}
      {{- end }}
    {{- end }}
    {{- if gt ($.Values.web.replicas | int) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {{ include "jitsi.webShard.selectorLabels" (merge (dict "RelativeScope" .) $) | nindent 16 }}
            topologyKey: kubernetes.io/hostname
    {{- end }}
      containers:
      - env:
        - name: DISABLE_HTTPS
          value: "1"
        - name: HTTP_PORT
          value: "{{ $.Values.web.httpPort }}"
        - name: XMPP_SERVER
          value: {{ include "jitsi.name" $ }}-shard-{{ $shard }}-prosody.{{ $.Release.Namespace }}.svc.cluster.local
        - name: JICOFO_AUTH_USER
          value: focus
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_BOSH_URL_BASE
          value: http://{{ include "jitsi.name" $ }}-shard-{{ $shard }}-prosody.{{ $.Release.Namespace }}.svc.cluster.local:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: {{ include "jitsi.sharedConfigMap.name" $ }}
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "jitsi.sharedConfigMap.name" $ }}
              key: PUBLIC_URL
      {{- if $.Values.web.extraEnvs }}
        {{- toYaml $.Values.web.extraEnvs | nindent 8 }}
      {{- end }}
      {{- if $.Values.web.image }}
        image: {{ $.Values.web.image }}
      {{- else }}
        image: jitsi/web:{{ $.Chart.AppVersion }}
      {{- end }}
        imagePullPolicy: {{ $.Values.web.imagePullPolicy }}
        name: web
        ports:
        - containerPort: {{ $.Values.web.httpPort }}
          protocol: TCP
          name: http
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: http
        startupProbe:
          httpGet:
            path: /robots.txt
            port: http
        livenessProbe:
          httpGet:
            path: /robots.txt
            port: http
      {{- with $.Values.web.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
        volumeMounts:
        {{- if $.Values.web.customConfig }}
        - mountPath: /config/custom-config.js
          name: custom-config
          subPath: custom-config.js
        {{ end }}
        {{- if $.Values.web.customUi }}
        - mountPath: /config/custom-interface_config.js
          name: custom-ui
          subPath: custom-interface_config.js
        {{ end }}
        {{- if $.Values.web.pluginHead }}
        - mountPath: /usr/share/jitsi-meet/plugin.head.html
          name: plugin-head
          subPath: plugin.head.html
        {{ end }}
        {{- if $.Values.web.welcomePageFooter }}
        - mountPath: /usr/share/jitsi-meet/static/welcomePageAdditionalContent.html
          name: welcome-page-footer
          subPath: welcomePageAdditionalContent.html
        {{ end }}
        {{- if $.Values.web.customWatermark }}
        - mountPath: /usr/share/jitsi-meet/images/watermark.png
          name: watermark
          subPath: watermark.png
        {{ end }}
      {{- if $.Values.web.extraVolumeMounts }}
        {{- toYaml $.Values.web.extraVolumeMounts | nindent 8 }}
      {{- end }}
      {{- with $.Values.web.extraContainerSpec }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if $.Values.web.customConfig }}
      - configMap:
          items:
          - key: custom-config.js
            path: custom-config.js
          name: {{ $.Values.web.customConfig.name }}
        name: custom-config
      {{ end }}
      {{- if $.Values.web.customUi }}
      - configMap:
          items:
          - key: custom-interface_config.js
            path: custom-interface_config.js
          name: {{ $.Values.web.customUi.name }}
        name: custom-ui
      {{ end }}
      {{- if $.Values.web.pluginHead }}
      - configMap:
          items:
          - key: plugin.head.html
            path: plugin.head.html
          name: {{ $.Values.web.pluginHead.name }}
        name: plugin-head
      {{ end }}
      {{- if $.Values.web.welcomePageFooter }}
      - configMap:
          items:
          - key: welcomePageAdditionalContent.html
            path: welcomePageAdditionalContent.html
          name: {{ $.Values.web.welcomePageFooter.name }}
        name: welcome-page-footer
      {{ end }}
      {{- if $.Values.web.customWatermark }}
      - configMap:
          items:
          - key: watermark.png
            path: watermark.png
          name: {{ $.Values.web.customWatermark.name }}
        name: watermark
      {{ end }}
    {{- if $.Values.web.extraVolumes }}
      {{- toYaml $.Values.web.extraVolumes | nindent 6 }}
    {{- end }}
{{ end }}
