{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    scope: jitsi
    service: {{ $.Values.web.name }}
    shard: {{ $shard | quote}}
  name: shard-{{ $shard }}-{{ $.Values.web.name }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    k8s-app: {{ $.Values.web.name }}
    scope: jitsi
    shard: {{ $shard | quote}}
{{- end }}
