{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ $.Values.web.name }}
    scope: jitsi
    shard: {{ $shard | quote}}
  name: shard-{{ $shard }}-{{ $.Values.web.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ $.Values.web.replicas }}
  selector:
    matchLabels:
      k8s-app: {{ $.Values.web.name }}
      scope: jitsi
      shard: {{ $shard | quote}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: {{ $.Values.web.name }}
        scope: jitsi
        shard: {{ $shard | quote}}
    spec:
    {{- with $.Values.web.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- if (($.Values.global).serviceAccount) }}
      serviceAccountName: {{ (($.Values.global).serviceAccount) }}
    {{- end }}
      containers:
      - env:
        - name: DISABLE_HTTPS
          value: "1"
        - name: HTTP_PORT
          value: "{{ $.Values.web.httpPort }}"
        - name: XMPP_SERVER
          value: shard-{{ $shard }}-{{ $.Values.prosody.name }}.{{ $.Release.Namespace }}.svc.cluster.local
        - name: JICOFO_AUTH_USER
          value: focus
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_BOSH_URL_BASE
          value: http://shard-{{ $shard }}-{{ $.Values.prosody.name }}.{{ $.Release.Namespace }}.svc.cluster.local:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: jitsi-config
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: jitsi-config
              key: PUBLIC_URL
      {{- if $.Values.web.extraEnvs }}
        {{- toYaml $.Values.web.extraEnvs | nindent 8 }}
      {{- end }}
      {{- if $.Values.web.image }}
        image: {{ $.Values.web.image }}
      {{- else }}
        image: jitsi/web:{{ $.Chart.AppVersion }}
      {{- end }}
        imagePullPolicy: {{ $.Values.web.imagePullPolicy }}
        name: web
        ports:
        - containerPort: {{ $.Values.web.httpPort }}
          protocol: TCP
          name: http
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: http
        startupProbe:
          httpGet:
            path: /robots.txt
            port: http
      {{- with $.Values.web.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
        volumeMounts:
        {{- if $.Values.web.customConfig }}
        - mountPath: /config/custom-config.js
          name: custom-config
          subPath: custom-config.js
        {{ end }}
        {{- if $.Values.web.customUi }}
        - mountPath: /config/custom-interface_config.js
          name: custom-ui
          subPath: custom-interface_config.js
        {{ end }}
        {{- if $.Values.web.pluginHead }}
        - mountPath: /usr/share/jitsi-meet/plugin.head.html
          name: plugin-head
          subPath: plugin.head.html
        {{ end }}
        {{- if $.Values.web.welcomePageFooter }}
        - mountPath: /usr/share/jitsi-meet/static/welcomePageAdditionalContent.html
          name: welcome-page-footer
          subPath: welcomePageAdditionalContent.html
        {{ end }}
        {{- if $.Values.web.customWatermark }}
        - mountPath: /usr/share/jitsi-meet/images/watermark.png
          name: watermark
          subPath: watermark.png
        {{ end }}
      {{- if $.Values.web.extraVolumeMounts }}
        {{- toYaml $.Values.web.extraVolumeMounts | nindent 8 }}
      {{- end }}
      volumes:
      {{- if $.Values.web.customConfig }}
      - configMap:
          items:
          - key: custom-config.js
            path: custom-config.js
          name: {{ $.Values.web.customConfig.name }}
        name: custom-config
      {{ end }}
      {{- if $.Values.web.customUi }}
      - configMap:
          items:
          - key: custom-interface_config.js
            path: custom-interface_config.js
          name: {{ $.Values.web.customUi.name }}
        name: custom-ui
      {{ end }}
      {{- if $.Values.web.pluginHead }}
      - configMap:
          items:
          - key: plugin.head.html
            path: plugin.head.html
          name: {{ $.Values.web.pluginHead.name }}
        name: plugin-head
      {{ end }}
      {{- if $.Values.web.welcomePageFooter }}
      - configMap:
          items:
          - key: welcomePageAdditionalContent.html
            path: welcomePageAdditionalContent.html
          name: {{ $.Values.web.welcomePageFooter.name }}
        name: welcome-page-footer
      {{ end }}
      {{- if $.Values.web.customWatermark }}
      - configMap:
          items:
          - key: watermark.png
            path: watermark.png
          name: {{ $.Values.web.customWatermark.name }}
        name: watermark
      {{ end }}
    {{- if $.Values.web.extraVolumes }}
      {{- toYaml $.Values.web.extraVolumes | nindent 6 }}
    {{- end }}
{{ end }}
