name: Lint Charts

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  lint-test:
    runs-on: cpu-s
    container: ubuntu
    steps:
      - name: Configure deps
        run: |
          apt update
          apt install -y unzip curl git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: |
          git config --global --add safe.directory  "$GITHUB_WORKSPACE"
          ct lint --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false --charts .
