name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: cpu-s
    container: ubuntu
    steps:

      - name: Configure deps
        run: |
          apt update
          apt install -y unzip curl git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global --add safe.directory  "$GITHUB_WORKSPACE"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Helm package
        run: |
          mkdir .cr-release-packages
          helm package .
          mv ./jitsi-*.tgz ./.cr-release-packages/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
        with:
          charts_dir: .
          skip_packaging: true
